import { SceneClient } from '../components/SceneClient.tsx'
import { CAMERA_STATIONS } from '../lib/camera-stations.ts'
import { getCameraStation } from '../lib/determinism-runtime.ts'
import { resolveRuntimeMode } from '../lib/runtime-config.ts'

/**
 * The capture entry point. This page resolves WDU_DETERMINISTIC,
 * WDU_STATION, and WDU_REDUCED_MOTION per request at the application boundary
 * and injects the resolved mode and station into the scene runtime. It is
 * force-dynamic so the mode is never baked into a static page at build time;
 * the copy below is still server-rendered into the initial HTML on every
 * request.
 */
export const dynamic = 'force-dynamic'

export default function Page() {
  const { mode, stationId, motion } = resolveRuntimeMode()
  getCameraStation(CAMERA_STATIONS, stationId)

  return (
    <main>
      <header className="site-header">
        <a className="skip-link" href="#scene-heading">
          Skip to the scene
        </a>
        <img
          src="/brand-mark.svg"
          alt=""
          width="28"
          height="28"
          className="brand-mark"
        />
        <span>Procedural Crystal</span>
      </header>

      <section className="hero" aria-labelledby="page-title">
        <p className="kicker">wdu-procedural-crystal · immersive evaluation fixture</p>
        <h1 id="page-title">
          A 532-triangle procedural crystal, Draco-compressed offline.
        </h1>
        <p className="lead">
          This fixture exercises the shared immersive contracts on a single asset
          generated by procedural-generation/generator.py (crystal-growth,
          Blender Python) and committed as a Draco-compressed GLB. Next.js
          renders this copy as HTML; the client-only canvas leaf loads the
          committed GLB through a local Draco decoder under /draco/, and the
          page makes no network fetch beyond what Next.js already serves.
        </p>
      </section>

      <section aria-labelledby="layout-heading">
        <h2 id="layout-heading">What stays where</h2>
        <dl className="contract-list">
          <div>
            <dt>Server-rendered page</dt>
            <dd>
              This copy and the motion control ship in the initial HTML. The
              canvas mounts only in the browser.
            </dd>
          </div>
          <div>
            <dt>One optimized procedural asset</dt>
            <dd>
              public/model/procedural-crystal.glb is the output of the documented
              inspect/validate/optimize pipeline (scripts/build-model.mjs),
              Draco-compressed with three's bundled decoder. The ready marker
              gates on its load, so readiness proves the model rendered.
            </dd>
          </div>
          <div>
            <dt>Local Draco decoder</dt>
            <dd>
              DRACOLoader.setDecoderPath('/draco/') resolves to the three decoder
              files committed under public/draco/. The runtime fetches no
              external URL; the manifest declares each decoder file explicitly.
            </dd>
          </div>
          <div>
            <dt>One camera owner</dt>
            <dd>
              CameraRig applies the selected camera station before every
              render. No other component writes camera position, target, or
              field of view.
            </dd>
          </div>
          <div>
            <dt>One clock</dt>
            <dd>
              Every animation reads the injected SceneClock. Deterministic
              mode advances a fixed 1/60 s step per rendered frame.
            </dd>
          </div>
          <div>
            <dt>One asset manifest</dt>
            <dd>
              lib/asset-manifest.json lists every runtime asset: the brand
              mark, the two poster variants, the optimized GLB, and the three
              Draco decoder files.
            </dd>
          </div>
          <div>
            <dt>Wired determinism</dt>
            <dd>
              WDU_DETERMINISTIC=1 freezes the clock, seeds every named random
              stream, applies the requested camera station, and sets
              html[data-wdu-ready="true"] only after the stable frame renders.
            </dd>
          </div>
          <div>
            <dt>Art-directed poster</dt>
            <dd>
              Two composed SVG variants, desktop and portrait, mirror the live
              crystal. The poster is the fallback behind loading, the poster
              quality tier, missing WebGL, and context loss: never a blank frame.
            </dd>
          </div>
          <div>
            <dt>Reduced motion</dt>
            <dd>
              The motion control in the DOM switches between the full rotation
              and the seeded static pose. WDU_REDUCED_MOTION=1 locks the same
              state for capture.
            </dd>
          </div>
          <div>
            <dt>Portrait reframe</dt>
            <dd>
              A named crystal-portrait station reframes the crystal for tall
              viewports. Live mode selects it by orientation; deterministic
              capture requests it by id (WDU_STATION=crystal-portrait).
            </dd>
          </div>
          <div>
            <dt>Quality and telemetry surfaces</dt>
            <dd>
              The copied quality controller owns Poster/Low/Medium/High and
              DPR; the telemetry surface exposes the IP-03 document on
              window.__WDU_IMMERSIVE_TELEMETRY__, and the plugin verifier
              reads the same three budget gates the controller reports.
            </dd>
          </div>
          <div>
            <dt>Context-loss recovery</dt>
            <dd>
              When the WebGL context is lost, the poster and a restore action
              appear over the frame; the action mounts a fresh canvas.
            </dd>
          </div>
          <div>
            <dt>Provenance</dt>
            <dd>
              The crystal is generated procedurally by the IP-10B Blender
              generator and passed unchanged through the IP-10C
              inspect/validate/optimize pipeline. reports/model/summary.json
              commits every hash, count, and budget reading.
            </dd>
          </div>
        </dl>
      </section>

      <section aria-labelledby="scene-heading">
        <h2 id="scene-heading">The scene</h2>
        <p>
          The subject is the procedural crystal — 30 segments grown from a
          single seed, merged by the optimize pipeline into 2 meshes (one per
          material) sharing 2 draw calls, with 532 visible triangles and zero
          textures. The Draco extension adds 1 metadata-only entry per mesh;
          the runtime decodes it with three's bundled JS decoder served
          locally under /draco/.
        </p>
        <SceneClient mode={mode} stationId={stationId} motion={motion} />
      </section>

      <section aria-labelledby="run-heading">
        <h2 id="run-heading">Run it</h2>
        <ol className="run-steps">
          <li>
            <code>npm ci</code> installs the exact locked dependency set,
            including the pinned <code>@gltf-transform/cli@4.4.2</code> used
            by the asset pipeline.
          </li>
          <li>
            <code>npm run build</code> produces the production bundle; the
            model, posters, and Draco decoder files are committed, so the
            build needs no network.
          </li>
          <li>
            <code>
              WDU_DETERMINISTIC=1 npm run start
            </code>{' '}
            is the capture entry point: fixed clock, seeded streams, named
            station.
          </li>
          <li>
            <code>
              node tests/immersive/evaluation/run-implementation-evaluation.mjs \
              --fixture procedural-crystal --out /tmp/wdu-procedural-crystal
            </code>{' '}
            runs the implementation evaluation against the built fixture.
          </li>
        </ol>
      </section>

      <section aria-labelledby="matrix-heading">
        <h2 id="matrix-heading">Pinned dependency matrix</h2>
        <table className="matrix">
          <thead>
            <tr>
              <th scope="col">Package</th>
              <th scope="col">Version</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Next.js</td>
              <td>15.5.24</td>
            </tr>
            <tr>
              <td>React</td>
              <td>19.2.8</td>
            </tr>
            <tr>
              <td>three</td>
              <td>0.185.1</td>
            </tr>
            <tr>
              <td>@react-three/fiber</td>
              <td>9.7.0</td>
            </tr>
            <tr>
              <td>@gltf-transform/cli</td>
              <td>4.4.2</td>
            </tr>
            <tr>
              <td>TypeScript</td>
              <td>5.9.3</td>
            </tr>
            <tr>
              <td>Node.js</td>
              <td>22.18 or newer</td>
            </tr>
          </tbody>
        </table>
      </section>
    </main>
  )
}